version: 2
	jobs:
	  build:
	    working_directory: ~/gallery
	    docker:
	      - image: circleci/node:8.16.0
	    steps:
	      - checkout
	      - restore_cache:
	          keys:
	            - v1-dependencies-{{ checksum "package.json" }}
	            # fallback to using the latest cache if no exact match is found
	            - v1-dependencies-
	      - run: npm ci
        # - run: npm install
	      - save_cache:
	          paths:
	            - node_modules
	          key: v1-dependencies-{{ checksum "package.json" }}
	      - run: npm test
